### ISSUE TITLE
Update Bolt Account Address to Bolt

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/solidus_bolt#82]
When a new address is added in the user AddressBook it should be added to the bolt account through the API https://help.bolt.com/api-bolt/#tag/Account/operation/AddAddress

We can fire a specific event at this [point](https://github.com/solidusio/solidus/blob/547d4eab818796ae77d0bd743359865ab189d069/core/app/models/concerns/spree/user_address_book.rb#L101) to decouple the logic and add the address to bolt account.

**Comment by nickhoffman** [comment]
Note that Bolt's API only supports adding addresses right now, but we're updating our API to support updating and deleting addresses. I'll keep you posted when updating and deleting are available.

**Comment by Naokimi** [comment]
I have a small worry about this task. Since we already have implemented code that imports all address from Bolt and saves them locally, if we were to send all the local address to Bolt without the option to update existing ones we'd run the risk of an infinite loop. As far as I understand on Solidus' side it shouldn't be much of an issue as we always display only 2 addresses, but I wonder about Bolt's side.

In any case to deal with this task for the time being we could add a new column to address `bolt_id` and check its presence before syncing on either side.

**Comment by DanielePalombo** [comment]
Considering that Solidus doesn't allow to update the address, I think that adding a `bolt_id` on the address won't fix the problem. I think that the only way to avoid address duplication at Bolt side will be to check all the addresses related to the account and skip address creation if another similar address is already present.

**Comment by nickhoffman** [comment]
Bolt's API should support updating and deleting addresses early next week.

@Naokimi, how would an infinite loop occur if syncing addresses from Bolt to Solidus detected when a Bolt address already exists in Solidus?

In Solidus, what's the relationship between a User and a User Address Book? Multiple addresses can be stored in an [address book](https://solidus.stoplight.io/docs/solidus/e24578b529b98-get-user-address-book), but the [Get User API](https://solidus.stoplight.io/docs/solidus/5a468afa9ec9a-get-user) returns a "bill address" and "ship address". Are those the default billing and shipping addresses that are set from a user's collection of addresses?

**Comment by Naokimi** [comment]
AFAIU yes, those two address are the ones that get displayed (on the app and in the API), and the address book has only those 2 addresses, but any address added or modified gets created as a separate record in the DB.
